name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker compose version # Usa docker compose en lugar de docker-compose

      - name: Build and run Docker Compose
        run: |
          docker compose up --build -d # Cambia docker-compose a docker compose

      - name: Run tests
        run: docker exec devops-practice-container npm test

      - name: Stop and clean Docker Compose
        run: |
          docker compose down # ambiar docker-compose a docker compose
